# Generated by Django 4.0.4 on 2022-05-30 15:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_image_category_image_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_att',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
